version: "3"

tasks:
  lint:
    desc: Lints the code and reports on issues.
    cmds:
      - python3 -m poetry black --check whisper_transcriber
      - python3 -m poetry pylint whisper_transcriber
      - python3 -m poetry mypy whisper_transcriber
  install:
    desc: Installs the package.
    cmds:
      - poetry install