name: Python package

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:

      fail-fast: true

      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Download Task & Verify Checksum
      run: |
        wget https://github.com/go-task/task/releases/download/v3.30.1/task_linux_amd64.deb
        echo "22f29aba72c80ca3e974bc86da0ad46ba4e5098b4b7435cdf88b83ed603c3c48 task_linux_amd64.deb" | sha256sum --check --status
        if [ $? -ne 0 ]; then echo "Checksum verification failed!"; exit 1; fi
    
    - name: Install Task
      run: |
        sudo dpkg -i task_linux_amd64.deb
        sudo apt-get install -f


    - name: Install and upgrade pip and poetry
      run: |
        python3 -m pip install --upgrade pip poetry


    - name: Install Dependencies
      run: |
        task install

    - name: Lint code
      run: |
        task lint